- name: Install Docker, AWS CLI, microk8s, nginx
  hosts: all
  become: true

  tasks:
# Install Docker on Ubuntu using official Docker repo
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker via official repo
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

# Install AWS CLI on Ubuntu
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages for AWS CLI
      apt:
        name:
          - curl
          - unzip
        state: present

    - name: Download AWS CLI installer
      get_url:
        url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
        dest: "/tmp/awscliv2.zip"

    - name: Unzip AWS CLI installer
      unarchive:
        src: "/tmp/awscliv2.zip"
        dest: "/tmp"
        remote_src: yes

    - name: Run AWS CLI installer
      command: "/tmp/aws/install"

    - name: Verify AWS CLI installation
      command: "aws --version"
      register: aws_cli_version

    - name: Display AWS CLI version
      debug:
        msg: "{{ aws_cli_version.stdout }}"

# install nginx
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Add user to group root
      user:
        name: "ubuntu"
        groups: root
        state: present

    - name: Remove default nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    # - name: Add nginx configuration
    #   copy:
    #     src: <control-node-path-to>/static-site-config
    #     dest: /etc/nginx/sites-available/
    #     owner: "{{ user }}"
    #     group: root
    #     mode: '0644'

    # - name: Enable website configuration
    #   file:
    #     src: /etc/nginx/sites-available/static-site-config
    #     dest: /etc/nginx/sites-enabled/static-site-config
    #     state: link

    - name: Ensure nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes

# install microk8s
    - name: Install microk8s
      snap:
        name:
          - microk8s
        classic: yes
        state: latest
      become: true
    
    - name: Add user to microk8s group
      user:
        name: ubuntu
        groups: microk8s
        append: yes
      become: true

    - name: Enable DNS and storage addons
      command: microk8s enable dns storage
      become: true