# FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
# WORKDIR /App
# # Copy everything
# COPY *.csproj ./
# # Restore
# RUN dotnet restore

# COPY . ./
# # Publish
# RUN dotnet publish -o out

# # Build runtime image
# FROM mcr.microsoft.com/dotnet/aspnet:7.0
# WORKDIR /App
# COPY --from=build /App/out .

# ENV ASPNETCORE_URLS="http://+:8080"
# # ENV ASPNETCORE_HTTPS_PORT=443

# EXPOSE 8080
# # EXPOSE 443
# ENTRYPOINT ["dotnet", "MagicVilla_VillaAPI.dll"]

# Build stage
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src

COPY *.csproj .
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app

COPY --from=build /app/publish .

# ASP.NET Core default port inside docker
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT="Development"
EXPOSE 8080

ENTRYPOINT ["dotnet", "MagicVilla_VillaAPI.dll"]
