# runtime only not builder
FROM mcr.microsoft.com/dotnet/aspnet:7.0 
WORKDIR /dotnet-app

COPY ./dotnet-app/publish .

RUN useradd -r -s /bin/false appuser && \
    chown -R appuser /dotnet-app
USER appuser

EXPOSE 8080

ENV ASPNETCORE_URLS=http://0.0.0.0:8080

# debug purposes
# RUN apt-get update && apt-get upgrade -y && apt-get install curl net-tools -y && netstat -tlnp

# Define the entry point for the container
ENTRYPOINT ["dotnet"]
CMD ["MagicVilla_VillaAPI.dll"]