name: Infrastructure Provision

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: [Linux]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init
        working-directory: MagicVilla_VillaAPI/Terraform/env/prod

      - name: Terraform Plan
        run: terraform plan
        working-directory: MagicVilla_VillaAPI/Terraform/env/prod

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: MagicVilla_VillaAPI/Terraform/env/prod
      
      - name: debug inventory
        run: cat MagicVilla_VillaAPI/Ansible/inventory.yaml

      - name: Upload inventory
        uses: actions/upload-artifact@v4
        with:
          name: ansible-inventory
          path: MagicVilla_VillaAPI/Ansible/inventory.yaml
       
  ansible:
    runs-on: [Linux]
    needs: terraform
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download inventory
        uses: actions/download-artifact@v4
        with:
          name: ansible-inventory
          path: MagicVilla_VillaAPI/Ansible/inventory.yaml

      # Save SSH private key from GitHub Secrets
      - name: Create SSH Key
        run: |
          rm -f /tmp/key.pem
          echo "${{ secrets.KEY }}" > /tmp/key.pem
          chmod 600 /tmp/key.pem

      - name: Apply Playbook to configure the server
        run: ansible-playbook -i inventory.yaml playbook.yaml
        working-directory: MagicVilla_VillaAPI/Ansible



      


          
