name: CI/CD .NET App

on:
  push:
    branches: [ "dev"]

env:
  IMAGE_NAME: magicvilla_villaapi

jobs:
    prepare: 
      runs-on: [Linux]
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Get version
          run: |
            ls -la
            ls -la MagicVilla_VillaAPI
            grep -oP '(?<=<Version>)[^<]+' MagicVilla_VillaAPI/MagicVilla_VillaAPI.csproj
            VERSION=$(grep -oP '(?<=<Version>)[^<]+' MagicVilla_VillaAPI/MagicVilla_VillaAPI.csproj)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
            echo "version: \"$VERSION\"" > version.yaml
            ls -l

        - name:  Debugging the extracted Version
          run: echo $VERSION

        - name: Upload Version artifact
          uses: actions/upload-artifact@v4
          with:
            name: version
            path: version.yaml

    build:
      runs-on: [Linux]
      needs: prepare
      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        env:
          DOTNET_INSTALL_DIR: /home/ubuntu/.dotnet  # writable by runner user
            
      - name: Add dotnet to PATH
        run: echo "/home/ubuntu/.dotnet" >> $GITHUB_PATH

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Load version into enviroment
        run: |
            VERSION=$(grep 'version' version.yaml | cut -d'"' -f2)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Package dotnet app
        run: dotnet publish -c Release -o ./publish
        working-directory: ${{ github.workspace }}/MagicVilla_VillaAPI

      - name: Get version
        run: |
          ls -la
          ls -la MagicVilla_VillaAPI

      - name: Upload dist artifacts to S3
        run: |
          aws s3 cp ./publish s3://shaymaahamdan/dotnet-app/publish-${{ env.VERSION }} --recursive
        working-directory: ${{ github.workspace }}/MagicVilla_VillaAPI
            
    docker:
      runs-on: [Linux]
      needs: build
      outputs:
        ecr_uri: ${{ steps.get_ecr.outputs.ecr_uri }}

      steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Terraform Init
      #   run: terraform init
      #   working-directory: MagicVilla_VillaAPI/Terraform/env/prod

      - name: Get ECR URI from Terraform output
        id: get_ecr
        run: |
          df -h
           du -sh ~/* | sort -rh | head -20
          terraform init
          echo "ECR_URI=$(terraform output -raw repository_url)" >> $GITHUB_ENV

        working-directory: MagicVilla_VillaAPI/Terraform/env/prod
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: version

      - name: Load version into enviroment
        run: |
            VERSION=$(grep 'version' version.yaml | cut -d'"' -f2)
            echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Debugging the extracted Version
        run: echo $VERSION

      - name: Download artifact from S3
        run: |
          aws s3 cp s3://shaymaahamdan/dotnet-app/publish ./MagicVilla_VillaAPI/publish-${{ env.VERSION }}  --recursive

      - name: debugging artifact
        run: |
            ls -l ./MagicVilla_VillaAPI
            ls -l ./MagicVilla_VillaAPI/publish-${{ env.VERSION }}
          
      - name: Build and push image 
        uses: docker/build-push-action@v6 
        with:
          context: .
          file: MagicVilla_VillaAPI/dockerfile
          push: true
          tags: ${{ needs.docker.outputs.ecr_uri }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
