name: Infrastructure Provision

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  installation:
    runs-on: [Linux]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Terraform Plan
        run: terraform plan


          
