# name: Test Self-Hosted Runner

# on:
#   workflow_dispatch:
#   push:
#     branches:
#       - main

# jobs:
#   installation:
#     runs-on: [Linux]

#     steps:
#       - name: 
#         run: |
          
